### ISSUE TITLE
[npm_rabbitmq] Fix deprecation warnings

### ISSUE THREAD

**Issue by RaviPatel** [FunNode/npm-rabbitmq#8]
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'assertQueue' of undefined
    at Rabbitmq.bind (/home/node/app/node_modules/@funnode/rabbitmq/index.js:70:19)
    at setup (/home/node/app/utils/setup.js:103:22)
    at <anonymous>
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by RaviPatel** [comment]
No longer seeing the error
